
## Appendix B: distribution of prime and target looking times

```{r fig-dist-prime}
#| label: fig-dist-prime
#| fig-height: 4
#| fig-width: 8
looking_times |> 
	mutate(prime_time = cut(prime_time, 
							seq(0, 1.5, 0.1),
							labels = FALSE,
							include.lowest = TRUE)) |> 
	add_count(lp, age_group, name = "n_total") |> 
	count(lp, age_group, prime_time, n_total) |> 
	mutate(n = n / n_total) |> 
	ggplot(aes(prime_time, n)) +
	facet_grid(lp~age_group) +
	annotate(geom = "rect",
			 fill = "orange",
			 ymin = -Inf,
			 ymax = Inf,
			 xmin = 0,
			 xmax = 0.75*10,
			 alpha = 1/3,
			 colour = NA) +
	# annotate(label = "Excluded trials",
	# 		 geom = "text",
	# 		  x = (0.75/2)*10,
	# 		  y = 1)
	geom_col(fill = "black") +
	labs(x = "Prime looking time (s)",
		 y = "Proportion of trials") +
	scale_x_continuous(labels = \(x) x/10) +
	theme(panel.grid.major.y = element_line(linetype = "dotted",
											colour = "grey"))
```

```{r fig-dist-target}
#| label: fig-dist-target
#| fig-height: 4
#| fig-width: 8
looking_times |> 
	mutate(target_time = cut(target_time, 
							 seq(0, 2, 0.1),
							 labels = FALSE,
							 include.lowest = TRUE)) |> 
	add_count(lp, age_group, name = "n_total") |> 
	count(lp, age_group, target_time, n_total) |> 
	mutate(n = n / n_total) |> 
	ggplot(aes(target_time, n)) +
	facet_grid(lp~age_group) +
	# annotate(label = "Excluded trials",
	# 		 geom = "text",
	# 		  x = (0.75/2)*10,
	# 		  y = 1)
	geom_col(fill = "black") +
	labs(x = "Targets looking time (s)",
		 y = "Proportion of trials") +
	scale_x_continuous(labels = \(x) x/10) +
	theme(panel.grid.major.y = element_line(linetype = "dotted",
											colour = "grey"))
```

{{< pagebreak >}}

