---
---


```{r define_model, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
fit <- model_fits_relaxed$fit
```

#### Model details

We fit a multilevel regression model using the `lmer` function of the `lme4` package, used the following formula:

```
elog ~ age_group + trial_type * lp * (ot1 + ot2 + ot3) +
(1 + ot1 + ot2 + ot3 + trial_type + age_group | participant)
```

The formal implementation of this model is:

$$

\color{white}{
\log \Bigg( \frac{p}{n - q} \Bigg) = (\beta_{0} + \beta_{0p} + \beta_{0i}) + ... \\
(\beta_{1} + \beta_{1p} + \beta_{1i}) \times Age_{pi} + ... \\
(\beta_{2} + \beta_{2p} + \beta_{2i}) \times Vocabulary_{pi} + ... \\
(\beta_{3} + \beta_{3p} + \beta_{3i})\times Condition_{pi} + ... \\
(\beta_{4} + \beta_{4i}) \times Group_{pi} + ... \\
(\beta_{5} + \beta_{5i}) \times (Vocabulary_{pi} \times Group_{pi}) + ... \\
(\beta_{6} + \beta_{6i}) \times (Vocabulary_{pi} \times Condition_{pi}) + ... \\
(\beta_{7} + \beta_{7i}) \times (Condition_{pi} \times Group_{pi}) + ... \\
(\beta_{8} + \beta_{8i}) \times (Vocabulary_{pi} \times Group_{pi} \times Condition_{pi}) + \varepsilon_{pi}
}
$$


#### Fixed effects


```{r fixed_effects_table, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
draws <- gather_draws(fit, `b_.*`, `sigma`, regex = TRUE)

draws %>% 
	mean_qi(.width = c(0.95, 0.50)) %>% 
	pivot_wider(names_from = .width, values_from = c(.value, .lower, .upper)) %>% 
	clean_names() %>% 
	select(-c(point, interval, value_0_5)) %>% 
	gt(rowname_col = "variable") %>% 
	fmt_number(2:6) %>% 
	cols_merge(c("lower_0_95", "upper_0_95"), pattern = "[{1}, {2}]") %>% 
	cols_merge(c("lower_0_5", "upper_0_5"), pattern = "[{1}, {2}]") %>% 
	cols_label(
		variable = md("**Predictor**"),
		value_0_95 = md("**Mean**"),
		lower_0_95 = md("**95% CrI**"),
		lower_0_5 = md("**50% CrI**")
	) %>% 
	tab_style(
		style = list(
			cell_fill(color = "#b9fac4")
		),
		locations = cells_body(
			columns = lower_0_95,
			rows = lower_0_95 > 0
		)
	) %>% 
	tab_style(
		style = list(
			cell_fill(color = "#b9fac4")
		),
		locations = cells_body(
			columns = lower_0_5,
			rows = lower_0_5 > 0
		)
	) %>% 
	tab_style(
		style = list(
			cell_fill(color = "#fabfb9")
		),
		locations = cells_body(
			columns = lower_0_95,
			rows = upper_0_95 < 0
		)
	) %>% 
	tab_style(
		style = list(
			cell_fill(color = "#fabfb9")
		),
		locations = cells_body(
			columns = lower_0_5,
			rows = upper_0_5 < 0
		)
	) %>% 
	as_raw_html()
```


```{r main_effects_plot, echo=FALSE, message=FALSE, warning=FALSE}

draws %>% 
	filter(!str_detect(.variable, "time_bin|sigma")) %>% 
	mutate(.value = ifelse(.variable=="b_Intercept", inv_logit_scaled(.value), .value/4)) %>% 
	ggplot(aes(.value, .variable, fill = stat(cut_cdf_qi(cdf, labels = percent, .width = c(0.50, 0.80, 0.95))))) +
	geom_vline(xintercept = 0, colour = "white") +
	stat_halfeye(point_color = "white", interval_color = "white") +
	labs(x = "Value", y = "Variable", fill = "CrI") +
	scale_fill_brewer(direction = -1, na.translate = FALSE) +
	theme(
		axis.title = element_blank(),
		legend.position = "top"
	)

```

#### Random effects


```{r random_effects_participant, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

vcov(fit) %>% 
	cov2cor() %>% 
	as.data.frame() %>% 
	rownames_to_column("term1") %>% 
	pivot_longer(-term1, names_to = "term2", values_to = ".value") %>% 
	ggplot(aes(fct_rev(term1), term2, fill = .value)) +
	geom_tile() +
	labs(x = "Term 1", y = "Term 2", fill = "Posterior correlation") +
	scale_fill_distiller(limits = c(-1, 1)) +
	coord_equal() +
	theme(
		legend.position = "top",
		legend.text = element_text(size = 8),
		axis.title = element_blank(),
		axis.text.y = element_text(hjust = 1, size = 7),
		axis.text.x = element_text(angle = 90, hjust = 1, size = 7)
	)

```


#### Marginal means {.tabset }

##### Overall

```{r gaze_relaxed_time, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
sample_size <- participants_stringent %>% 
	filter(valid_participant) %>% 
	count(lp)

n <- expand_grid(
	lp = c("Monolingual", "Bilingual"),
	age_group = c("25 months"),
	trial_type = unique(gaze_relaxed$trial_type),
	time_bin_center = seq(min(gaze_relaxed$time_bin_center), max(gaze_relaxed$time_bin_center), 0.5)
)

m <- epred_draws(object = fit, newdata = n, ndraws = 20, re_formula = NA) %>% 
	mutate(.value = logit_to_prob(.epred))

ggplot(m, aes(time_bin_center, .value)) +
	facet_wrap(~fct_rev(lp)) +
	geom_hline(yintercept = 0.5, colour = "white") +
	geom_line(aes(group = interaction(age_group, trial_type, lp, .draw),
				  colour = trial_type),
			  alpha = 0.15, size = 0.65) +
	stat_summary(aes(group = trial_type, colour = trial_type),
				 fun = mean, geom = "line", size = 1.25) +
	stat_summary(data = gaze_relaxed, aes(y = logit_to_prob(logit_adjusted), group = trial_type,
										  colour = trial_type),
				 fun.data = mean_se, geom = "errorbar", size = 0.5, na.rm = TRUE,
				 position = position_dodge(width = 0.3)) +
	geom_text(data = sample_size, aes(x = min(gaze_relaxed$time_bin_center), y = 0.95, label = paste0("N = ", n)),
			  colour = "white", hjust = 0, size = 5) +
	labs(x = "Time bin (100 ms)", y = "Expected posterior mean PTLT", colour = "Trial type",
		 fill = "Trial type", shape = "Trial type", linetype = "Trial type") +
	scale_color_brewer(palette = "Set1") +
	scale_x_continuous(breaks = min(gaze_relaxed$time_bin_center):max(gaze_relaxed$time_bin_center), labels = unique(gaze_relaxed$time_bin)) +
	scale_y_continuous(limits = c(0, 1), labels = percent) + 
	theme(
		legend.position = "top",
		legend.title = element_blank(),
		axis.text.x = element_text(size = 9),
		panel.grid.major.x = element_blank(),
		panel.grid.minor.x = element_blank()
	)
```



##### {-}

#### {-}

