---
---


```{r define_model_2125_mon_stringent, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
fit_2125_mon <- model_fits$fit_2125_mon
```


```{r fixef_2125_mon_stringent, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
main_effects <- confint.merMod(fit_2125_mon, method = "Wald") %>% 
	as.data.frame() %>% 
	clean_names() %>% 
	drop_na(x2_5_percent) %>%
	rownames_to_column("term") %>% 
	right_join(clean_names(tidy(fit_2125_mon, effects = "fixed"))) %>% 
	select(term, estimate, std_error, conf_lower = x2_5_percent, conf_upper = x97_5_percent,
		   statistic, df, p_value) %>% 
	gt() %>% 
	fmt_number(2:7) %>% 
	fmt_number(8, decimals = 3) %>% 
	cols_merge(starts_with("conf_"), pattern = "[{1}, {2}]") %>% 
	cols_label(
		term = md("**Predictor**"),
		estimate = md("**Estimate**"),
		std_error = md("**SE**"),
		conf_lower = md("**CI<sub>95%</sub>**"),
		statistic = md("***t***"),
		df = md("**df**"),
		p_value = md("***p***")
	) %>% 
	tab_style(
		style = list(
			cell_fill(color = "#ffc7a1")
		),
		locations = cells_body(
			columns = everything(),
			rows = p_value < 0.05
		)
	)

main_effects

```



```{r gaze_time_2125_mon_stringent, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, fig.dim = c(6.5, 5)}
sample_size <- augment(fit_2125_mon) %>%
	distinct(participant, age_group) %>% 
	count(age_group)

augment(fit_2125_mon) %>% 
	mutate(.fitted_prob = logit_to_prob(.fitted)) %>% 
	ggplot(shape = trial_type, linetype = trial_type) +
	facet_wrap(~age_group, ncol = 1) +
	geom_hline(yintercept = 0.5, size = 1, colour = "grey") +
	stat_summary(aes(x = ot1, y = .fitted_prob, colour = trial_type, fill = trial_type),
				 fun.data = mean_se, geom = "ribbon", alpha = 0.5, colour = NA) +
	# stat_summary(aes(x = ot1, y = .fitted_prob,
	# 				 group = interaction(participant, trial_type),
	# 				 colour = trial_type, fill = trial_type),
	# 			 fun = mean, geom = "line", alpha = 0.25, size = 0.5) +
	stat_summary(aes(x = ot1, y = .fitted_prob, colour = trial_type, fill = trial_type),
				 fun = mean, geom = "line", size = 1) +
	stat_summary(aes(x = ot1, y = logit_to_prob(elog), colour = trial_type, fill = trial_type), fun.data = mean_se, geom = "pointrange", size = 0.25) +
	geom_text(data = sample_size,
			  aes(x = -0.3, y = 0.95, label = paste0("N = ", n)),
			  show.legend = FALSE,
			  colour = "black", fill = "black") +
	labs(x = "Time bin (100 ms)", y = "Pr(Target fixation)",
		 colour = "Prime type", fill = "Prime type",
		 shape = "Prime type", linetype = "Prime type") +
	scale_y_continuous(limits = c(0, 1), labels = percent) + 
	scale_x_continuous(breaks = unique(gaze$ot1), labels = unique(gaze$time_bin)) +
	theme(
		axis.title.y = element_blank(),
		axis.text = element_text(size = 7),
		legend.position = "left"
	) +
	
	augment(fit_2125_mon) %>% 
	mutate(elog_prob = logit_to_prob(elog)) %>% 
	group_by(participant, age_group, trial_type) %>% 
	summarise(elog_prob = mean(elog_prob, na.rm = TRUE)) %>% 
	ggplot(aes(trial_type, elog_prob, fill = trial_type, colour = trial_type)) +
	facet_wrap(~age_group, ncol = 1) +
	geom_hline(yintercept = 0.5, size = 1, colour = "grey") +
	geom_violin(show.legend = FALSE) +
	geom_boxplot(width = 0.1, outlier.colour = NA, fill = "white", colour = "black") +
	labs(x = "Trial type", y = "Pr(Target fixation)",
		 colour = "Trial type", fill = "Prime type") +
	scale_y_continuous(limits = c(0, 1), labels = percent) + 
	theme(
		axis.title = element_blank(),
		axis.ticks = element_blank(),
		axis.text.x = element_blank(),
		axis.text.y = element_blank()
	) +
	plot_layout(ncol = 2, guides = "collect", widths = c(0.75, 0.25)) &
	plot_annotation(
		caption = "(A) Marginal means of the Growth Curve analysis model (100 ms time bins), plotted in separate\npanels for 21- and 25-month olds. Sample sizes are indicated at the upper left corner in each panel.\n(B) Mean observed probability of target looking, aggregated across time bins.",
		tag_levels = "A"
	) &
	theme_custom() &
	theme(
		legend.position = "right",
		plot.caption = element_text(size = 10, hjust = 0),
		plot.caption.position = "plot"
	)
```

