---
---


### Frequency {.tabset }


#### CHILDES {.tabset }

##### Prime

```{r stimuli_frequency_childes_prime, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=5, out.width="80%"}

stimuli %>% 
	distinct(location, test_language, target, prime, .keep_all = TRUE) %>% 
	ggplot(aes(trial_type, frequency_prime_childes, colour = trial_type, fill = trial_type)) +
	facet_wrap(location~test_language) +
	geom_violin() +
	geom_boxplot(colour = "black", fill = "white", size = 0.75, outlier.colour = NA, width = 0.1) +
	# geom_jitter(colour = "white", size = 1, shape = 1,
	# 			width = 0.1, alpha = 0.5, stroke = 1) +
	labs(x = "Trial type", y = "Lexical frequency (Zipf score)",
		 colour = "Trial type", fill = "Trial type") +
	theme(
		legend.position = "none",
		legend.title = element_blank(),
		axis.text = element_text(size = 9),
		axis.title.x = element_blank(),
		panel.grid.major.x = element_blank(),
		panel.grid.major.y = element_line(colour = "grey", linetype = "dotted"),
		plot.caption = element_text(size = 10, hjust = 0),
	)

```

##### Target

```{r stimuli_frequency_childes_target, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=5, out.width="80%"}
stimuli %>% 
	distinct(location, test_language, target, prime, .keep_all = TRUE) %>% 
	ggplot(aes(trial_type, frequency_target_childes, colour = trial_type, fill = trial_type)) +
	facet_wrap(location~test_language) +
	geom_violin() +
	geom_boxplot(colour = "black", fill = "white", size = 0.75, outlier.colour = NA, width = 0.1) +
	# geom_jitter(colour = "black", size = 1, shape = 1,
	# 			width = 0.1, alpha = 0.5, stroke = 1) +
	labs(x = "Trial type", y = "Lexical frequency (Zipf score)",
		 colour = "Trial type", fill = "Trial type") +
	theme(
		legend.position = "none",
		legend.title = element_blank(),
		axis.text = element_text(size = 9),
		axis.title.x = element_blank(),
		panel.grid.major.y = element_line(colour = "grey", linetype = "dotted"),
		plot.caption = element_text(size = 10, hjust = 0),
	)
```

##### {-}


#### {-}

### Familiarity {.tabset }

#### Prime

```{r stimuli_familiarity_prime, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=7, out.width="100%"}
means <- stimuli %>% 
	distinct(location, test_language, target, trial_type, prime, .keep_all = TRUE) %>% 
	group_by(test_language, location, trial_type) %>% 
	summarise(
		familiarity_prime = mean(familiarity_prime, na.rm = TRUE),
		.groups = "drop"
	) %>% 
	drop_na()

stimuli %>% 
	distinct(location, test_language, target, prime, .keep_all = TRUE) %>% 
	# mutate(prime = reorder_within(target, familiarity_prime, list(location, test_language))) %>% 
	ggplot(aes(familiarity_prime, reorder(prime, familiarity_prime),  colour = trial_type, fill = trial_type,
			   xmin = familiarity_prime-familiarity_se_prime, xmax = familiarity_prime-familiarity_se_prime)) +
	facet_wrap(location~test_language, scales = "free_y") +
	# geom_vline(xintercept = 0.5, size = 1, colour = "grey") +
	geom_vline(data = means, aes(xintercept = familiarity_prime, colour = trial_type), size = 1) +
	# geom_errorbar() +
	geom_point() +
	labs(x = "% of infants that understand", y = "Prime word",
		 colour = "Trial type", fill = "Trial type") +
	scale_x_continuous(labels = percent, limits = c(0, 1)) +
	theme(
		legend.position = "top",
		legend.title = element_blank(),
		axis.text = element_text(size = 7),
		axis.title.y = element_blank(),
		panel.grid.major.y = element_blank(),
		plot.caption = element_text(size = 10, hjust = 0),
	)

```

#### Target

```{r stimuli_familiarity_target, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=6.5, out.width="100%"}
means <- stimuli %>% 
	distinct(location, test_language, target, trial_type, prime, .keep_all = TRUE) %>% 
	group_by(test_language, location, trial_type) %>% 
	summarise(
		familiarity_target = mean(familiarity_target, na.rm = TRUE),
		.groups = "drop"
	) 

stimuli %>% 
	distinct(location, test_language, target, prime, .keep_all = TRUE) %>% 
	ggplot(aes(familiarity_target, reorder(target, familiarity_target), colour = trial_type, fill = trial_type)) +
	facet_wrap(location~test_language, scales = "free_y") +
	# geom_vline(xintercept = 0.5, size = 1, colour = "grey") +
	geom_vline(data = means, aes(xintercept = familiarity_target, colour = trial_type), size = 1) +
	# geom_errorbar() +
	geom_point() +
	labs(x = "% of infants that understand", y = "Target word",
		 colour = "Trial type", fill = "Trial type") +
	scale_x_continuous(labels = percent, limits = c(0, 1)) +
	# scale_y_reordered() +
	theme(
		legend.position = "top",
		legend.title = element_blank(),
		axis.text = element_text(size = 7),
		axis.title.y = element_blank(),
		panel.grid.major.y = element_blank(),
		plot.caption = element_text(size = 10, hjust = 0),
	)


```


#### {-}


### Animacy

```{r stimuli_animacy, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=6, out.width="100%"}

animacy <- stimuli %>%
	distinct(location, test_language, target, prime, .keep_all = TRUE) %>% 
	pivot_longer(c(is_animate_prime, is_animate_target), names_to = "role", values_to = "is_animate") %>% 
	mutate(role = str_to_sentence(str_remove(role, "is_animate_"))) %>% 
	count(location, test_language, trial_type, role, is_animate) %>% 
	drop_na(is_animate) %>% 
	mutate(is_animate = ifelse(is_animate, "Animate", "Inanimate"))


animacy %>% 
	filter(role=="Prime") %>% 
	ggplot(aes(trial_type, n, fill = is_animate, colour = is_animate)) +
	facet_wrap(location~test_language, ncol = 4) +
	geom_col(position = position_fill(), colour = "#0D1117") +
	geom_vline(xintercept = 0.5, size = 1, colour = "grey") +
	labs(title = "Prime", x = "Trial type", y = "# trials", colour = "Animacy", fill = "Animacy") +
	scale_y_continuous(labels = percent) +
	coord_flip() + 
	theme(
		axis.title.x = element_blank()
	) +
	
	animacy %>% 
	filter(role=="Target") %>% 
	ggplot(aes(trial_type, n, fill = is_animate, colour = is_animate)) +
	facet_wrap(location~test_language, ncol = 4) +
	geom_col(position = position_fill(), colour = "#0D1117") +
	geom_vline(xintercept = 0.5, size = 1, colour = "grey") +
	labs(title = "Target", x = "Trial type", y = "# trials", colour = "Animacy", fill = "Animacy") +
	scale_y_continuous(labels = percent) +
	coord_flip() +
	
	plot_layout(guides = "collect", ncol = 1) &
	theme(
		legend.position = "top",
		legend.title = element_blank(),
		panel.grid = element_blank(),
		axis.title.y = element_blank(),
		axis.text = element_text(size = 7),
		strip.text = element_text(size = 11)
	)


```

### Semantic category

```{r stimuli_category, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=6, out.width="100%"}

stimuli %>% 
	distinct(location, test_language, target, prime, .keep_all = TRUE) %>% 
	pivot_longer(c(category_prime, category_target), names_to = "role", values_to = "category") %>% 
	mutate(role = str_to_sentence(str_remove(role, "category_"))) %>% 
	drop_na(trial_type, category) %>% 
	count(trial_type, test_language, location, role, category) %>% 
	ggplot(aes(n, trial_type, colour = category, fill = category, order = n)) +
	facet_wrap(role~location~test_language) +
	geom_col(position = position_fill(), colour = "#0D1117", size = 1) +
	labs(x = "% of trials", y = "Trial type",
		 colour = "Trial type", fill = "Trial type") +
	scale_x_continuous(labels = percent) +
	theme(
		legend.position = "top",
		legend.title = element_blank(),
		axis.text = element_text(size = 9),
		axis.title.y = element_blank(),
		plot.caption = element_text(size = 10, hjust = 0),
	)

```


### {-}
