source("renv/activate.R")
if ("targets" %in% installed.packages()) library(targets)
run <- function() job::job({targets::tar_make()})
message('Welcome! To execute the repository, 1) run renv::restore(), 2) and then make() in your R console.')
message('Check https://github.com/bilingual-project/cognate-priming for instructions, documentation, and troubleshooting.')
