project:
  render:
    - manuscript.qmd

format:
  arxiv-pdf:
    keep-tex: true  
    linenumbers: true
    doublespacing: false
    runninghead: "Parallel "
    include-in-header: 
      text: |
        \usepackage{tipa}
        \usepackage{booktabs}
    knitr:
      opts_chunk:
        dev: "cairo_pdf"
    filters: 
      - "_extensions/andrewheiss/wordcount/citeproc.lua"
      - "_extensions/andrewheiss/wordcount/wordcount.lua"

title: "Developmental trajectories of bilingual word recognition"
short-title: "Developmental trajectories of bilingual word recognition"
author:
  - name: Gonzalo Garcia-Castro
    corresponding: true
    orcid: 0000-0002-8553-4209
    email: gonzalo.garciadecastro@upf.edu
    affiliations:
      - id: cbc
        name: Universitat Pompeu Fabra
        department: Center for Brain and Cognition
        city: Barcelona, 08005
  - name: Serene Siow
    orcid: 0000-0001-6482-2191
    email: siow.serene@gmail.com
    affiliations: 
      - id: ul
        name: University of Oxford
        department: Department of Experimental Psychology
        city: Oxford, OX2 6GG
  - name: Nuria Sebastian-Galles
    orcid: 0000-0001-6938-2498
    email: nuria.sebastian@upf.edu
    affiliations: 
      - ref: cbc
  - name: Kim Plunkett
    orcid: 0000-0003-0216-7480
    email: kim.plunkett@psy.ox.ac.uk
    affiliations: 
      - ref: oxf
keywords:
  - cognate
  - word recognition
  - vocabulary
  - bilingualism
  - growth curve analysis
  - bayesian
csl: "../assets/apa7.csl"
bibliography: "../assets/references.bib"
link-citations: true
editor: source
lang: en
freeze: true
fig-dpi: 1000
