---
title: "Parallel activation and the developing bilingual lexicon: a longitudinal study on word recognition"
author: "Gonzalo García-Castro"
date: "25/01/2022"
output:
  pdf_document:
    latex_engine: xelatex
bibliography: "../../references.bib"
---


Previous studies suggest that bilinguals access their lexicon in a language non-selective way: recognising and producing words in one language activates word representations in the other [e.g., @costa2000cognate; @thierry2007brain]. This parallel activation of both languages seems to be already present during toddlerhood [e.g., @von2012language], but its impact on the developing lexicon remains unclear. We investigated this issue by testing bilingual toddlers in a primed word recognition task adapted from @mani2010infant. In each trial, participants were first presented with a prime picture in silence. Then, two more pictures were presented side by side, and one of them (target picture) was named in participants’ dominant language. We registered participants’ looking preference for the target picture as an indicator of word recognition. We manipulated the phonological overlap between the prime and the target labels, and the cognate status of the prime label. This allowed us to test whether bilingual toddlers generated an implicit label for the prime picture (presented in silence), and whether they did so in only the language of test, or in both languages. Following Mani and Plunkett’s findings, we expected participants to generate an implicit label for the prime picture, which should interfere with the subsequent recognition of the target word when both labels share phonological overlap. Under the hypothesis that bilingual participants would activate labels for the prime pictures in both languages, we further predicted that interference would be stronger after cognate primes (labels from both languages overlap with the target word) than after non-cognate primes (only the label in the language of test overlaps with the target word). We tested bilingual toddlers and same-aged monolingual controls at three age points: 21, 25, and 30 months to investigate if and how parallel activation of both languages emerged or changed across these ages. We present preliminary data from this ongoing study and discuss the potential theoretical implications of the data collected so far.

## References
