---
title: "Stimuli"
output: github_document
always_allow_html: true
date: "`r paste0('Updated: ', format(Sys.Date(), '%d/%m/%Y'))`"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = TRUE,
	warning = TRUE, 
	cache.extra = knitr::rand_seed,
	out.width = "80%",
	results = "asis",
	dpi = 300,
	dev.args = list(png = list(type = "cairo"))
)
options(
	knitr.kable.NA = '-',
	knitr.duplicate.label = "allow",
	ggplot2.discrete.fill = pal_d3()(4),
	ggplot2.discrete.colour = pal_d3()(4)
)


```


```{r params, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

# load objects
tar_load_globals()
tar_load(stimuli)

theme_set(theme_custom()) # in utils.R
```


# Frequency {.tabset }

## CHILDES {.tabset }

### Prime

```{r stimuli_frequency_childes_prime, echo=FALSE, fig.height=5, message=FALSE, warning=FALSE, out.width="80%", paged.print=TRUE}

stimuli %>% 
	distinct(test_language, target, prime, .keep_all = TRUE) %>% 
	ggplot() +
	aes(
		x = trial_type, 
		y = frequency_prime_childes, 
		colour = trial_type, 
		fill = trial_type
	) +
	facet_wrap(~test_language) +
	geom_boxplot(
		colour = "black",
		fill = "white", 
		size = 1, 
		outlier.colour = NA,
		width = 0.1
	) + 
	geom_point(
		shape = 1, 
		stroke = 1.25,
		size = 3,
		position = position_jitter(
			width = 0.1,
			seed = 888
		)
	) +
	labs(
		x = "Trial type", 
		y = "Lexical frequency (Zipf score)",
		colour = "Trial type", 
		fill = "Trial type"
	) +
	theme(
		legend.position = "none",
		axis.title.x = element_blank(),
		panel.grid.major.y = element_line(colour = "grey", linetype = "dotted"),
	)

ggsave(here("img", "stimuli_frequency_prime_childes.png"))

```

### Target

```{r stimuli_frequency_childes_target, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=5, out.width="80%"}
stimuli %>% 
	distinct(
		test_language, 
		target,
		prime,
		.keep_all = TRUE
	) %>% 
	ggplot() +
	aes(
		x = trial_type, 
		y = frequency_target_childes, 
		colour = trial_type,
		fill = trial_type
	) + 
	facet_wrap(~test_language) +
	geom_boxplot(
		colour = "black", 
		fill = "white",
		size = 1,
		outlier.colour = NA, 
		width = 0.1
	) +
	geom_point(
		shape = 1, 
		stroke = 1.25,
		size = 3,
		position = position_jitter(
			width = 0.1,
			seed = 888
		)
	) +
	labs(
		x = "Trial type",
		y = "Lexical frequency (Zipf score)",
		colour = "Trial type",
		fill = "Trial type"
	) +
	theme(
		legend.position = "none",
		axis.title.x = element_blank(),
		panel.grid.major.y = element_line(colour = "grey", linetype = "dotted"),
	)

ggsave(here("img", "stimuli_frequency_target_childes.png"))


```



# Familiarity {.tabset }

## Prime

```{r stimuli_familiarity_prime, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=7, out.width="100%"}
means <- stimuli %>% 
	distinct(test_language, target, trial_type, prime, .keep_all = TRUE) %>% 
	group_by(test_language, trial_type) %>% 
	summarise(
		familiarity_prime = mean(familiarity_prime, na.rm = TRUE),
		.groups = "drop"
	) %>% 
	drop_na()

stimuli %>% 
	distinct(test_language, target, prime, .keep_all = TRUE) %>% 
	# mutate(prime = reorder_within(target, familiarity_prime, list(location, test_language))) %>% 
	ggplot() +
	aes(
		familiarity_prime, 
		reorder(prime, familiarity_prime),
		colour = trial_type, 
		fill = trial_type,
		xmin = familiarity_prime-familiarity_se_prime,
		xmax = familiarity_prime+familiarity_se_prime
	) +
	facet_wrap(~test_language, scales = "free_y") +
	geom_vline(
		data = means, 
		aes(
			xintercept = familiarity_prime, 
			colour = trial_type
		),
		size = 1
	) +
	geom_errorbar(width = 0) +
	geom_point() +
	labs(
		x = "% of infants that understand",
		y = "Prime word",
		colour = "Trial type", 
		fill = "Trial type"
	) +
	scale_x_continuous(
		labels = percent,
		limits = c(0, 1)
	) +
	theme_custom() +
	theme(
		legend.position = "top",
		legend.title = element_blank(),
		axis.text.y = element_text(size = 7),
		axis.title.y = element_blank(),
		panel.grid.major.x = element_line(colour = "grey", linetype = "dotted"),
		plot.caption = element_text(size = 10, hjust = 0),
	)

ggsave(here("img", "stimuli_familiarity_prime.png"))


```

## Target

```{r stimuli_familiarity_target, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=6.5, out.width="100%"}
means <- stimuli %>% 
	distinct(test_language, target, trial_type, prime, .keep_all = TRUE) %>% 
	group_by(test_language, trial_type) %>% 
	summarise(
		familiarity_target = mean(familiarity_target, na.rm = TRUE),
		.groups = "drop"
	) 

stimuli %>% 
	distinct(test_language, target, prime, .keep_all = TRUE) %>% 
	ggplot() +
	aes(
		x = familiarity_target, 
		y = reorder(target, familiarity_target), 
		colour = trial_type,
		fill = trial_type,
		xmin = familiarity_target-familiarity_se_target,
		xmax = familiarity_target+familiarity_se_target
	) +
	facet_wrap(
		~test_language, 
		scales = "free_y"
	) +
	# geom_vline(xintercept = 0.5, size = 1, colour = "grey") +
	geom_vline(
		data = means,
		aes(
			xintercept = familiarity_target,
			colour = trial_type
		), 
		size = 1
	) +
	geom_errorbar(width = 0) +
	geom_point(
		shape = 1,
		size = 0.5,
		stroke = 1
	) +
	labs(
		x = "% of infants that understand",
		y = "Target word",
		colour = "Trial type",
		fill = "Trial type"
	) +
	scale_x_continuous(
		labels = percent,
		limits = c(0, 1)
	) +
	# scale_y_reordered() +
	theme_custom() +
	theme(
		legend.position = "top",
		legend.title = element_blank(),
		axis.text.y = element_text(size = 7),
		axis.title.y = element_blank(),
		panel.grid.major.y = element_blank(),
		plot.caption = element_text(size = 10, hjust = 0),
	)
ggsave(here("img", "stimuli_familiarity_target.png"))


```


# Animacy

```{r stimuli_animacy, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=6, out.width="100%"}

animacy <- stimuli %>%
	distinct(
		test_language, 
		target, 
		prime, 
		.keep_all = TRUE
	) %>% 
	pivot_longer(
		c(is_animate_prime, is_animate_target), 
		names_to = "role",
		values_to = "is_animate"
	) %>% 
	mutate(role = str_to_sentence(str_remove(role, "is_animate_"))) %>% 
	count(
		test_language, 
		trial_type,
		role,
		is_animate
	) %>% 
	drop_na(is_animate) %>% 
	mutate(is_animate = ifelse(is_animate, "Animate", "Inanimate"))


animacy %>% 
	filter(role=="Prime") %>% 
	ggplot() +
	aes(
		x = trial_type, 
		y = n, 
		fill = is_animate,
		colour = is_animate
	) + 
	facet_wrap(~test_language, ncol = 4) +
	geom_col(position = position_fill()) +
	geom_hline(
		yintercept = 0.5, 
		size = 1,
		colour = "grey"
	) +
	labs(
		title = "Prime", 
		x = "Trial type", 
		y = "# trials",
		colour = "Animacy", 
		fill = "Animacy"
	) +
	scale_fill_d3() +
	scale_colour_d3() +
	scale_y_continuous(labels = percent) +
	coord_flip() + 
	theme(
		axis.title.x = element_blank()
	) +
	
	animacy %>% 
	filter(role=="Target") %>% 
	ggplot(aes(trial_type, n, fill = is_animate, colour = is_animate)) +
	facet_wrap(~test_language, ncol = 4) +
	geom_col(position = position_fill()) +
	geom_hline(yintercept = 0.5, size = 1, colour = "grey") +
	labs(title = "Target", x = "Trial type", y = "# trials", colour = "Animacy", fill = "Animacy") +
	scale_y_continuous(labels = percent) +
	coord_flip() +
	scale_fill_d3() +
		scale_colour_d3() +

	plot_layout(guides = "collect", ncol = 1) &
	theme(
		legend.position = "top",
		legend.title = element_blank(),
		panel.grid = element_blank(),
		axis.title.y = element_blank(),
		axis.text = element_text(size = 7),
		strip.text = element_text(size = 11)
	)

ggsave(here("img", "stimuli_animacy.png"))

```


# Semantic category

```{r stimuli_category, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE, fig.height=6, out.width="100%"}

stimuli %>% 
	distinct(
		test_language, 
		target, 
		prime,
		.keep_all = TRUE
	) %>% 
	pivot_longer(
		c(category_prime, category_target),
		names_to = "role",
		values_to = "category"
	) %>% 
	mutate(role = str_to_sentence(str_remove(role, "category_"))) %>% 
	drop_na(
		trial_type,
		category
	) %>% 
	count(
		trial_type, 
		test_language, 
		role, 
		category,
		name = "sum"
	) %>% 
	right_join(
		expand(
			.,
			trial_type, 
			test_language, 
			role, 
			category
		)
	) %>%
	replace_na(list(sum = 0)) %>% 
	group_by(trial_type, test_language, role) %>% 
	mutate(
		n =  sum(sum),
		prop = sum/n
	) %>% 
	ungroup() %>% 
	ggplot() +
	aes(
		x = prop,
		y = reorder_within(category, desc(prop), list(trial_type, role, test_language)),
		fill = test_language,
		order = prop
	) + 
	facet_wrap(
		trial_type~role~test_language,
		scales = "free_y", labeller = label_wrap_gen(multi_line = FALSE)
	) +
	geom_col(
		colour = "white",
		position = position_dodge(),
		width = 1
	) +
	labs(
		x = "% of trials",
		y = "Trial type",
		colour = "Trial type",
		fill = "Trial type"
	) +
	scale_fill_d3(palette = "category10") +
	scale_x_continuous(labels = ~percent(., accuracy = 1)) +
	scale_y_reordered() +
	theme(
		legend.position = "none",
		legend.title = element_blank(),
		axis.text.y = element_text(size = 9, hjust = 1),
		axis.text.x = element_text(size = 8, hjust = 1),
		axis.title.y = element_blank(),
		axis.ticks.y = element_blank(),
		plot.caption = element_text(size = 10, hjust = 0),
		panel.grid.major.x = element_line(colour = "grey", linetype = "dotted"),
		strip.text = element_text(size = 10)
	)

ggsave(here("img", "stimuli_semantic-category.png"), width = 15, dpi = 2000)


```

