---
title: "Sanity checks"
format: pdf
echo: false
message: false
warning: false
---

```{r setup}
# load target objects
targets::tar_load_globals()
targets::tar_load(c(participants, stimuli, 
					attrition_trials,
					attrition_participants,
					gaze_aoi, vocabulary,
					data_time, data_summary))

# set ggplot theme and colour palette
theme_set(theme_ggdist()) # set custom ggplot theme

clrs <- c("#003f5c", "#58508d", "#bc5090", "#ff6361", "#ffa600")

options(ggplot2.ordinal.fill = clrs[c(1, 4, 5)],
		ggplot2.ordinal.colour = clrs[c(1, 4, 5)],
		ggplot2.discrete.fill = clrs[c(1, 4, 5)],
		ggplot2.discrete.colour = clrs[c(1, 4, 5)],
		ggplot2.continuous.fill = ggplot2::scale_color_gradient,
		ggplot2.continuous.colour = ggplot2::scale_color_gradient)
```

```{r fig-target-timecourse}
#| label: fig-target-timecourse
#| fig-height: 9
#| fig-width: 12
#| fig-cap: "Time course of the empirical logit of target fixations. Data are presented separately for each target picture \\(named\\), with different colours indicating data generated by participants of different age groups. Depicted data correspond to trials in which participants were reported to understand the target word in the vocabulary checklist. All other inclusion criteria have been applied. Thin lines correspond to fixation trajectories from individual participants. Each thicker line corresponds to the mean fixation trajectory of each age group."
data_time |> 
	summarise(.logit = mean(.logit), 
			  .by = c(id, target, age_group, target, timebin, trial_type)) |>
	ggplot(aes(timebin, .logit,
			   colour = age_group,
			   group = interaction(id, age_group))) +
	geom_smooth(se = FALSE, alpha = 0.15, linewidth = 0.15) +
	facet_wrap(~target) +
	geom_smooth(aes(group = age_group),
				se = FALSE,
				method = 'loess',
				formula = 'y ~ x') +
	labs(x = "Time bin (100 ms)",
		 y = "Empirical logit of target fixations\n(Target + 0.5)/(Distractor + 0.5)",
		 colour = "Age group",
		 fill = "Age group")
```