---
---

```{r setup}
#| label: setup
#| echo: false
#| message: false
#| warning: false
# load objects
targets::tar_config_set(store = here::here("_targets"),
						script = here::here("_targets.R"))

targets::tar_load_globals()

targets::tar_load(
	c(participants,
	  stimuli,
	  vocabulary,
	  attrition_trials, 
	  attrition_participants,
	  bvq_data, 
	  gaze_aoi, 
	  data_time, 
	  data_aggr,
	))

targets::tar_load(
	c(model_fits_aggr,
	  model_fits_time,
	  model_loos_aggr,
	  model_loos_time
	))

# prepare data
attrition <- lst(participants,
				 attrition_participants,
				 attrition_trials) |> 
	reduce(inner_join, by = join_by(session_id)) |> 
	unnest_wider(matches("all"), names_sep = "_")

library(knitr)
library(kableExtra)
library(ggplot2)
library(gt)
library(patchwork)
library(english)
library(gtExtras)

# set ggplot theme and colour palette

my_theme <- theme_minimal() +
	theme(panel.grid = element_blank(),
		  axis.line = element_line(colour = "black"),
		  text = element_text(size = 12, colour = "black"),
		  axis.text = element_text(colour = "black"))

theme_set(my_theme)

clrs <- c("#003f5c", "#58508d", "#bc5090", "#ff6361", "#ffa600")

options(ggplot2.ordinal.fill = clrs[c(1, 4, 5)],
		ggplot2.ordinal.colour = clrs[c(1, 4, 5)],
		ggplot2.discrete.fill = clrs[c(1, 4, 5)],
		ggplot2.discrete.colour = clrs[c(1, 4, 5)],
		ggplot2.continuous.fill = ggplot2::scale_color_gradient,
		ggplot2.continuous.colour = ggplot2::scale_color_gradient)

set.seed(888)



```


# Introduction

## The early lexicon

Building a mental lexicon is a major achievement in the developmental journey of infants: by accumulating lexical representations of familiar words, infants are later able to recognise them in speech, and to extract meaning from the speech they are exposed to. Infants start forming their first lexical representations before their first year of life [@jusczyk1999; @halle1994; @vihman2004]. When presented with pairs of pictures of familiar objects, 6-months-old infants already direct their gaze towards whichever is named [@bergelson20126; @bergelson2015early]. This initial lexicon is hardly larger than around fifteen words [@REFERENCE], but it undergoes rapid growth [@REFERENCE] during their second year of life, at the end of which toddlers know an average of XXX words, and by 30 months of age, they know XXX words [@REFERENCE]. This accelerated lexical developmental during the second year of life is also reflected in infants'  trajectories of word recognition: infants recognise familiar words faster and more efficiently [@fernald1998rapid; @fernald2001half; @hurtado2007spoken]. Bilingual infants' trajectories of lexical acquisition [@hoff2012, @de2014bilingual; @pearson1994patterns; @byers-heinlein2023sometimes] and word recognition [@vihman2007onset; @vihman2013; @legacy2018vocabulary] are equivalent to their monolingual peers'. This is a remarkable deed: bilingual infants receive a relative impoverished linguistic input in each of their languages compared to monolinguals [@costa2014does]. The mechanism that facilitate bilingual lexical development are still unclear.

## (Early) Word recognition is cascaded

Despite their different linguistic input, monolinguals and bilinguals share broadly common word recognition mechanisms. The first step towards spoken word-recognition is the acoustic-phonetic processing of the speech signal. This results in the activation of lexical representations whose associated phonological forms matches the acoustic signal to some extent. The activated word-forms then compete for selection: the lexical system uses the auditory input, together with top-down context provided by grammatical, supra-segmental, and semantic constraints, to select the candidate lexical representation with the best match. There is evidence that spoken word recognition occurs in a *cascaded* fashion. The activation and selection of candidate lexical representations overlap in time, relying on partial information that accumulates as the speech signal unfolds [@marslen1987functional; @marslen1978processing; @grosjean1980spoken]. This cascaded activation triggered by lexical access also results in the activation of the concepts associated to the accesses phonological forms. @allopenna1998tracking.

This is also the case of the developing lexicon: like adults, infants activate non-selected lexical representations. This is relfected by the fact that from 21 months of age, infants' lexicon seems to be systematically organised accordi to the semantic and phnological properties of the lexical representations.

SEMANTICS
@arias2009lexical showed evidence of semantic priming in 21-month-old infants. In a word recognition task, infants' recognition of a spoken word (e.g., *dot*) was interfered by the previous presentation of a semantically related word (e.g., *cat*). Later studies provided electrophysiological evidence of such effect as early as 14 months of age [@friedrich2005lexical]. 

PHONOLOGY
Initial lexical representations are also phonologically well-specified [@swingley2000spoken; @swingley2002lexical]. Overall these results suggest that early lexical representations are systematically organised in the lexicon according to their semantic and phonological properties.


BOTH
@chow2017spoken adapted the Visual World Paradigm from @huettig2007tug to explore 24- to 30-month-old toddlers' visual fixation patterns during a word recognition when presented with phonological and semantic distractors. In each trial, the authors presented participants with four semantically and phonologically pictures. Four seconds after pictures onset, a word-form was auditorily presented. The word did not refer to any of the pictures displayed on the screen, but was phonologically related to one of them (both labels shared phonological onset), and semantically related to another one of the pictures (both referents belonged to the same taxonomic category. For instance, participants might be presented with the pictures of a sandwich, a bus, a cat, and a dress. Then they would hear the carrier phrase "Look at the **bee**!". The authors registered participants fixations to the phonological and semantic distractors, and found evidence of a preference for the phonological distractor at earlier stages of the post-naming phase, and a preference for the semantic distractor at later stages of the trial. These results support a cascaded activation account of lexical access during the first stages of lexical development. @swingley1999continuous


## Cascaded activation in bilingual parallel activation

There is also evidence of cascaded activation in bilinguals. A critical property of bilingual language processing, both in adults and infants, is that of non-selective access to the lexicon. When listening to speech, bilinguals activate all lexical candidates from either language consistent with the speech signal. Even more surprising, when speaking, bilinguals activate all potential words consistent with the concepts they want to express. This effect has been systematically reported in adults [@marian1999activation; @costa2000cognate; @thierry2007brain; @dunabeitia2009masked].



For instance, previous work on lexical acquisition has provided some insight into how  found that English-Spanish bilinguals' vocabulary in English was influenced by the words they had already acquired in Spanish. This is consistent with previous accounts of lexical acquisition in which infants acquire new words through preferential acquisition [@hill2013, @fourtassi2020]. 

A monograph by @floccia2018introduction provided evidence of a language distance effect, where bilinguals learning two languages sharing higher lexical similarity knew more words in their less dominant language than those learning two language with lower lexical similarity. Later work by @mitchell2022cognate and @garcia-castro@cognate provided evidence for a more direct facilitation effect of cognateness. Cognates are form-similar translation equivalents. Cognateness is suggested to facilitate word acquisition through parallel activation: the co-activation of translation equivalents in speech might lead to an faster accumulation of learning instances with words, which ultimately results in an earlier age of acquisition.

Also in toddlers [@von2012language; @von2014bilinguals] and school-aged children [@persici2019lexical; @bosma2020cognate]. Some recent studies have investigated the recognition of mispronounced words comparing monolingual and bilingual toddlers. Overall, these studies do not find differences between monolinguals and bilinguals [@von2019impact; @wewalaarachchi2017vowels]. Evidence for differential processing of cognate and non-cognate words is provided by Ramon-Casas and colleagues who observed that Spanish-Catalan 24-month-olds were more prone to accept mispronunciations when the stimuli involved cognate words than when they involved non-cognate words [@ramon2009vowel; @ramon2010non].

Although recent work has provided strong evidence of parallel activation in early ages, how cognateness shapes that organisation of the early bilingual lexicon, and how this is reflected on the dynamics of lexical access during word comprehension and production is unclear.

Using the experimental paradigm developed by [@arias2009lexical; @arias2013s; @singh2014one] compared within and across language
priming effects in Chinese-English toddlers. @kuipers2015bilingualism compared ERP responses to picture-word pairs in English monolinguals and Welsh-English bilinguals where the words were either semantically related or unrelated to a pictured object. Although both studies tested 30-month-olds, the conclusions the authors reached do not fully agree. @singh2014one concluded that there is a discontinuity between adults and young children in the way the two lexicons interact, while @kuipers2010event and @kuipers2015bilingualism concluded that there are no differences in adults’ and toddlers’ lexical-semantic processing.

## Cognate word recogntiion 


@floccia2020translation tested 27-month-old simultaneous bilinguals in a cross-language priming paradigm. The two languages participants were learning were English, and an Additional Language (either Cantonese, Dutch, French, German, Greek, Italian, Mandarin, Polish, Portuguese, or Spanish). A prime word was embedded at the end of a carrier sentence that participants listened to. Then participants were presented with the auditory label of the target word, and two pictures were shown side-by-side, the target picture, and a distractor picture. In Study 1, the target word was the translation equivalent of the prime word (*cheese*-*fromage* for an English-French bilingual). In other trials, prime and target words were unrelated (e.g., *sock*-*fromage*). There was no phonological overlap at onset between prime and target or distractor labels in either of the two conditions. Participants were presented with two blocks of related and unrelated trials. In one of the blocks, participants were presented with English prime words and Home Language target words (*sock*-*fromage*), and in the other block they were presented with Additional Language prime words and English target words (*fromage*-*sock*). The authors found a cross-linguistic priming effect, in which participants showed a stronger preference for the target picture in the post-naming phase in related trials, as compared to unrelated trials. This effect was found regardless of the language of the prime (English or Home Language), or the dominance of the language of the prime (i.e., whether the prime word belonged to the dominant language). Target preference exceeded chance level in both conditions. In Study 2, the authors tested a similar group of bilinguals in a cross-linguistic semantic priming task, in which participants were primed with words in English, and tested with semantically related words in the Additional Language (or vice versa). This time, prime and target words were not translation equivalents, but rather words whose referents shared semantic features. Results from Study  2 were parallel to those from Study 1. The authors found a strong semantic priming effect across languages, regardless of the language of the prime or the dominance of the language of the prime. Overall these results suggest that bilinguals recognised target words in both conditions, and benefited from a cross-linguistic facilitation effect from translation equivalents. The symmetry of such effect across both languages suggests that participants lexical access occurred in parallel for the two members of translation equivalents. As @floccia2020translation note, the stimuli set of Study 2 contains multiple cognates, especially in languages with a larger degree of phonological overlap across translation pairs, like English and Dutch. The authors run *post hoc* analyses exploring the effect of cognateness on the cross-language priming effects found, which showed no evidence of a cognateness effect on target preference. However, the cross-language effects reported in Study 2 might still reflect the confounding influence of cognateness, as the resulting effect might have been generated by an interaction by the phonological and semantic overlap between cognate primes and targets.

Another source of evidence supporting the language non-selective account of lexical access is provided by cross-languistic priming priuming thorught translation paradigms. In line with @floccia2020translation, @von2012language found that bilingual toddlers aged 21-to-43-months, and who were learning German and English, showed a stronger target preference in a German word recognition task after being primed with a phonologically related English word, which shared phonological onset with the prime word (e.g., *slide*-*Klide* [German for *dress*]), compared to when prime and target words were phonologically unrelated (e.g., *bottle*-*Ohr* [German for *ear*]). Interestingly, they also found evidence of such priming effect when participants were prime with an English word which was *not* phonologically related to the German target word, but rather its German translation was (e.g., *leg* [with German trasnlation *Bein*]-*Stein* [German for *stone*]). Altogether, these results indicate that bilingual toddlers activate translation equivalents in parallel during word recognition, and that the phonology of both labels may interact with lexical access in the recognition of subsequet words. Importantly, cross-linguitic priming through translation demonstrates that previous findings of a cognateness facilitation in word production and recognition do not result from the mere phonological overlap between auditorily presented and target labels, but also from the phonological overlap between the prime translation (not presented) and the target.

Evidence from cognates.
Marian and Spivey (1999)
Costa et al. (2000)

@dijkstra2019multilink

The role of cognates in lexical processing.


Another source of evidence are studies studies involving phonological priming of non-cognates through translation. [SEE REFERENCES FROM VON HOLZEN 2012]

## The rpesent study

The aforementioned studies use priming-though-translation paradigms. In these paradigms, cross-linguistic priming results from activation spreading from the lexical representation of the the (auditorily presented) prime word to the lexical representation of its translation through semantic associations (e.g., translation equivalence). When prime words are auditorily presented, the task design constraints the naming context to one of the languages. The consequence is a potential asymmtry between the activation dynamics of the lexical representation of both labels: while the participant has heard one label, the activation of its translation must spread across semantic links. This might lead to a lower strength, and higher lacenty of the activation of the translation.


In the present study, we use an adaptation of an implicit naming paradigm by @mani2010infant, in which participants are primed with a picture, instead of an auditorily presented label. @mani2010infant showed that 18 month-old monolinguals implicitly generate the labels of name-known pictures presented in silence. In each trial, infants were presented with prime pictures presented in silence, and then with a target and a distractor picture, both presented side-by-side. Finally, the target picture's label was presented auditorily. The authors manipulated the phonological overlap between the prime label and the target label, so that in half of the trials both labels were phonologically related, sharing phonological onset (*cat*-*cup*), or phonologically unrelated (*ball*-*comb*). Prime and target-distractor pairs were semantically unrelated. Interestingly, infants showed a stronger looking preference for the target picture after phonologically related prime pictures, compared to after phonologically unrelated primes. This suggests that infants implicitly named prime pictures despite such pictures having been presented in silence, and that the phonology of the resulting label interacted with the subsequent auditory recognition of the target label. In particular, the authors found a facilitation effect: target looking preference was stronger in phonologically related primes, indicating that the activated phonological segments of the generated prime label facilitated the subsequent activation of the phonological representation of the target label during recognition.

@mani2011phonological used the same paradigm in 24-months-old monolinguals, and also found evidence of implicit naming, but in the opposite direction. After phonologically related primes, infants showed weaker target looking preference than after phonologically unrelated primes. These results interpreted these outcome as the result of the implicitly generated prime label interfering with the subsequent recognition of the (phonologically related) target word. The authors suggested that the shift from facilitation to interference from 18 to 24 months they found in both studies might be the result of a developmental shift in which 18-month-olds' lexicon is not yet organised based on phonological similarity, while 24-month-olds' is. This would lead to the former showing a pre-lexical facilitation effect in which such facilitation occurs via the activation of phonological segments, while the latter would show an interference effect due to lateral links between lexical representation having been established. Both studies by Mani and Plunkett provide evidence of implicit naming of name-known pictures by 18-month old toddlers and older, and that the resulting labels interact with the dynamics of recognition of subsequently presented word-forms.

Even earlier evidence of implicit naming was provided through ERP registering at 14 months of age. @duta2012erp presented name-known pictures in silence for one second. After one second, the picture's label was presented auditorily, and the infants' N400 component was registered. In some trials the auditory label corresponded to a canonical realisation of the word-form. In other trials, the word was mispronounced. Infants ERP signal differed when presented with correct pronunciations or mispronunciations, indicating that infants had generated expectations at the phonological level about the auditory labels of the picture before they were presented with its auditory label. A later study by @styles2015infant re-analysed the first 1,000 ms of the trials in the previous study (while the picture was being presented before the auditory label was presented), and found that the ERPs of name-known pictures (according to parental reports of receptive vocabulary) differed from those of name-unknown pictures (which infants would not be able to lexicalise). This provides further support to the account that at around 14 months of age, infants already name familiar pictures, even if presented in silence.

When extended to the bilingual case, this implicit naming task may offer bilingual participants with an uncontrained naming context in whcih the activation of both labels may occur in a truly cascaded fashion for both languages in parallel: the recognition of the prime object depicted activates the (common) semantic representation for both members of the translation equivalent, and this in turn activates the two available phonological word-forms, one in each language. Using an adaptation of @mani2010infant's implicit naming paradigm, @von2014bilinguals provided evidence that bilingual adults generate implicit labels in both labels for visually fixated pictures. The authors presented German-English bilinguals with 120 prime-target pairs. Primes were presented as familiar pictures in silence. After prime picture offset, target words were presented auditorily. Participants' N400 ERP components were recorded from target word onset. The authors manipulated the phonological relationship between the prime and target word-forms within participants' L1 and across L1 and L2. When prime and target were phonologically identical (*Affe*-*Affe*, German for *monkey*), or similar (*Fahne*-*Sahne*, German for *flag* and *ice-cream*, respectively) within L1, participants' showed a reduced N400 amplitude, compared to when prime and target were phonologically unrelated (*Messer*-*Seil*, German for *knife* and *rope*). Critically, a similar effect was found when prime and target were phonologically related through translation (*Rustsche*-*Kleid*, German for *slide* and *dress*). This suggests that participants activated prime labels in both languages in parallel, and that both labels impacted the dynamics of target words recognition.

Evidence from cognates.



The role of cognates in lexical processing.


This study also provides a more suitable design for drawing conslusions about developmental change in word recognition trajectories frot wo reasons. First, it extends the age range of participants, compared to previous studies. Second, participants were tested at three selected age points to ensure a more balanced sample size across ages. Third, the partially longitudinal design allows modelling the performance of participants across testing sessions altogether.

. In order to circumvent the problem of limited vocabulary knowledge
in the non-dominant language, we propose to test participants only in their dominant language, therefore
directing our research to the question of how possessing a second language affects processing of the
dominant one in bilingual toddlers [@costa2014does provide a fuller description of the
advantages of such approach].

## The present study

The present study is aimed at investigating the developmental trajectories of word recognition in bilingualism, and how (if at all) language non-selectivity shapes them. Using an adaptation of [@mani2010infants], we presented 20- to 32-months-old toddlers with a cross-linguistic phonological priming paradigm. We manipulated both the phonological overlap between the prime word and target word, and the cognate status of the prime word, to test the hypothesis that bilingual toddlers implicitly name familiar pictures in both languages. If so, phonological priming effect should be larger when the prime label in  both languages shares phonological overlap with the target words (cognate condition), compared to when only the label of the prime in one language overlaps phonologically with the target (non-cognate condition). We also also included a control *Unrelated* condition in which regardless of the cognate status of the prime word, neither of the prime labels in any language overlapped phonologically with the target word.

We compared the explanatory power of three measures of vocabulary size on participants' trajectories of word recognition: L1 vocabulary and total vocabulary.Previous studies suggest that same-language vocabulary size predicts better bilingual infants' performance in word recognition tasks, as compared to cross-language vocabulary size [@marchman2010vocabulary]