# process Oxford gaze data
library(Matrix)
library(lme4)
library(ggplot2)
library(eyetrackingR)
library(dplyr)
library(tidyverse)
library(multcomp)
library(readxl)


### Oxford data format only - recoding variables

# read data
#CPfiledir <- "C:/MATLAB/BilingualProject_2020/data/concatenated/CP/"
CPfiledir <- "Data/Gaze/Oxford/"

fnames <- dir(CPfiledir)

cognatepriming <- data.frame()

for (i in 1:length(fnames)){
	filename <- paste(CPfiledir, fnames[i], sep = "")
	temp <- read.csv(filename)
	cognatepriming <- bind_rows(cognatepriming, temp)
}

# generate a trackloss column by inverting the validity column generated by Mihaela's script
# trackloss_column treats "1" and NA as trackloss, other way around from overall.validity columnn
cognatepriming$OVERALL.TRACKLOSS <- cognatepriming$OVERALL.VALIDITY
cognatepriming$OVERALL.TRACKLOSS[cognatepriming$OVERALL.TRACKLOSS == 0] <- NA
cognatepriming$OVERALL.TRACKLOSS[cognatepriming$OVERALL.TRACKLOSS == 1] <- 0
cognatepriming$OVERALL.TRACKLOSS[is.na(cognatepriming$OVERALL.TRACKLOSS)] <- 1

# Recode extrapolated fixation points (-1) as fixation (1); recode NA as 0
# CP, NP, UN are prime AOIs
cognatepriming$VIS.CP.ISFXT[cognatepriming$VIS.CP.ISFXT == -1] <- 1
cognatepriming$VIS.CP.ISFXT[is.na(cognatepriming$VIS.CP.ISFXT)] <- 0
cognatepriming$VIS.NP.ISFXT[cognatepriming$VIS.NP.ISFXT == -1] <- 1
cognatepriming$VIS.NP.ISFXT[is.na(cognatepriming$VIS.NP.ISFXT)] <- 0
cognatepriming$VIS.UN.ISFXT[cognatepriming$VIS.UN.ISFXT == -1] <- 1
cognatepriming$VIS.UN.ISFXT[is.na(cognatepriming$VIS.UN.ISFXT)] <- 0

cognatepriming$VIS.TARGET.ISFXT[cognatepriming$VIS.TARGET.ISFXT == -1] <- 1
cognatepriming$VIS.TARGET.ISFXT[is.na(cognatepriming$VIS.TARGET.ISFXT)] <- 0
cognatepriming$VIS.DISTR.ISFXT[cognatepriming$VIS.DISTR.ISFXT == -1] <- 1
cognatepriming$VIS.DISTR.ISFXT[is.na(cognatepriming$VIS.DISTR.ISFXT)] <- 0


# CONDITIONS: Relatedness - CP & NP = 1, UN = 0
cognatepriming$Relatedness <- NA
cognatepriming$Relatedness = ifelse(is.na(cognatepriming$VIS.UN.STM.CODE), 1, 0)
cognatepriming$Relatedness <- as.factor(cognatepriming$Relatedness)


# CONDITIONS: Cognateness - CP = 1, NP & UN = 0
cognatepriming$Cognateness <- NA
cognatepriming$Cognateness = ifelse(is.na(cognatepriming$VIS.CP.STM.CODE), 0, 1)
cognatepriming$Cognateness <- as.factor(cognatepriming$Cognateness)


# 3 CONDITIONS
cognatepriming$Condition <- ifelse(
	(cognatepriming$Relatedness == "1" & cognatepriming$Cognateness == "0"), "Non-Cognate Prime", ifelse(
		(cognatepriming$Relatedness =="1" & cognatepriming$Cognateness == "1"), "Cognate Prime", ifelse(
			(cognatepriming$Relatedness =="0"), "Unrelated Prime", "NA")))
cognatepriming$Condition <- as.factor(cognatepriming$Condition)
cognatepriming$Condition <- factor(cognatepriming$Condition, levels = c("Unrelated Prime", "Non-Cognate Prime", "Cognate Prime")) # Reorder factor levels to specify a baseline (easier interpretation)


cognatepriming$PRIME.STM = paste(cognatepriming$VIS.CP.STM,cognatepriming$VIS.NP.STM,cognatepriming$VIS.UN.STM)


cognatepriming$Relatedness <- factor(cognatepriming$Relatedness, levels = c(0, 1), labels = c("Unrelated Prime", "Related Prime"))


cognatepriming = subset(cognatepriming, select = c(ID, TRIAL, AUD.STM, VIS.CP.STM, VIS.NP.STM, VIS.UN.STM, PRIME.STM, VIS.TARGET.STM, VIS.DISTR.STM, Timestamp, VIS.CP.ISFXT, VIS.NP.ISFXT, VIS.UN.ISFXT, VIS.TARGET.ISFXT, VIS.DISTR.ISFXT, OVERALL.TRACKLOSS, Cognateness, Relatedness, Condition))

cognatepriming <- cognatepriming %>%
	mutate(ID = factor(ID)) %>%
	mutate(PRIME.STM = str_trim(PRIME.STM, side = c("both", "left", "right"))) %>%
	mutate(VIS.TARGET.STM = str_trim(VIS.TARGET.STM, side = c("both", "left", "right"))) # trim white space for matching with CDI


# Read participant demographics and bind to experimental data
participant <- read_excel("Data/Participants/participant_oxford_Apr2021.xlsx") %>%
	mutate(ID = factor(ID))

cognatepriming <- left_join(cognatepriming, participant, by = "ID") %>%
	mutate(LangGroup = factor(LangGroup, levels = c("Monolingual", "Bilingual"))) %>%
	mutate(AgeGroup = factor(AgeGroup, levels = c("21 months", "25 months", "30 months")))

cognatepriming %>%
	dplyr::select(ID, LangGroup, AgeGroup) %>%
	unique() %>%
	group_by(LangGroup, AgeGroup) %>%
	tally()

# supplementary CDI list
supplementary_CDI_2020 <- read_excel("Data/Vocabulary/vocabulary_oxford_Apr2021.xlsx", sheet = "Supplementary") %>%
	gather(key = "ID", value = "score", -c(item)) %>%
	rename(word = item)

supplementary_CDI_2020$word[supplementary_CDI_2020$word == "boots"] <- "boot"
supplementary_CDI_2020$word[supplementary_CDI_2020$word == "fire engine"] <- "fireengine"

supplementary_CDI_known <- supplementary_CDI_2020 %>%
	filter(score == 1) %>%
	mutate(ID = as.factor(ID))

## Exclude specific trials for each participant based on CDI
cognatepriming2020 <- semi_join(cognatepriming, supplementary_CDI_known, by = c("ID")) %>%
	semi_join(., supplementary_CDI_known, by = c("ID", c("PRIME.STM" = "word"))) %>%
	semi_join(., supplementary_CDI_known, by = c("ID", c("VIS.TARGET.STM" = "word"))) # only keep trials when target is known


CDI_2019 <- read_excel("Data/Vocabulary/vocabulary_oxford_Apr2021.xlsx", sheet = "553-word") %>% # long format
	separate(item, c("category", "word"), " - ") %>%
	gather(key = "ID", value = "score", -c(word, category))

CDI_2019$word[CDI_2019$word == "teddy bear"] <- "teddy"
CDI_2019$word[CDI_2019$word == "bunny / rabbit"] <- "bunny"
CDI_2019$word[CDI_2019$word == "lorry / truck"] <- "truck"
CDI_2019$word[CDI_2019$word == "bicycle / bike"] <- "bike"
CDI_2019$word[CDI_2019$word == "boot(s)"] <- "boot"

CDI_trial_CDI_known <- CDI_2019 %>%
	filter(score == 1 | score == 2) %>%
	mutate(ID = as.factor(ID)) %>%
	filter(!(category == "Household objects" & word == "mouse")) %>%
	filter(!(category == "Food and Drink" & word == "fish")) %>%
	filter(!(category == "Food and Drink" & word == "chicken"))


cognatepriming2019 <- semi_join(cognatepriming, CDI_trial_CDI_known, by = c("ID")) %>%
	semi_join(., CDI_trial_CDI_known, by = c("ID", c("PRIME.STM" = "word"))) %>%
	semi_join(., CDI_trial_CDI_known, by = c("ID", c("VIS.TARGET.STM" = "word"))) %>% # only keep trials when target is known
	anti_join(., cognatepriming2020, by = "ID")


cognatepriming_clean <- bind_rows(cognatepriming2019, cognatepriming2020) %>%
	unique()

cognatepriming_clean %>%
	dplyr::select(ID, VIS.TARGET.STM) %>%
	unique() %>%
	group_by(ID) %>%
	summarise(n_trials_known = n(), .groups = "drop") %>%
	arrange(desc(n_trials_known))


# IDs without CDI data - look for data
missing_cdi <- anti_join(cognatepriming, cognatepriming_clean, by = "ID") %>%
	dplyr::select(ID) %>%
	unique()




## SETTING CRITERIA FOR DATA CLEANING
#### >50% Target/distractor looking

## Exclude trials with excessive trackloss in target/distractor window [4750 6750] - Timing for final version without lum baseline

data_target <- make_eyetrackingr_data(cognatepriming_clean, 
									  participant_column = "ID",
									  trial_column = "AUD.STM",
									  time_column = "Timestamp",
									  trackloss_column = "OVERALL.TRACKLOSS",
									  item_columns = c("PRIME.STM"),
									  aoi_columns = c('VIS.TARGET.ISFXT','VIS.DISTR.ISFXT', 'VIS.CP.ISFXT','VIS.NP.ISFXT','VIS.UN.ISFXT'), 
									  treat_non_aoi_looks_as_missing = FALSE)

# NOTE FOR CLEANING: Include center AOI - Looking at center of screen not judged as trackloss

#summary(data_target)

# set response window by specifying time after trial start
response_window_target <- subset_by_window(data_target, window_start_time = 4750, rezero= FALSE, remove= TRUE)
response_window_target <- subset_by_window(response_window_target, window_end_time = 6750, rezero= FALSE, remove= TRUE)

# analyze amount of trackloss by subjects and trials
(trackloss <- trackloss_analysis(data = response_window_target))

# Remove trials with over 50% trackloss
response_window_clean_target <- clean_by_trackloss(data = response_window_target, trial_prop_thresh = .5)

# Assess mean trackloss for each participant
trackloss_clean_target <- trackloss_analysis(data = response_window_clean_target)

#### >50% Prime looking

## Also exclude trials with insufficient prime looking time [2500 4000]

data_prime <- make_eyetrackingr_data(cognatepriming_clean, 
									 participant_column = "ID",
									 trial_column = "AUD.STM",
									 time_column = "Timestamp",
									 trackloss_column = "OVERALL.TRACKLOSS",
									 item_columns = c("PRIME.STM"), 
									 aoi_columns = c('VIS.CP.ISFXT','VIS.NP.ISFXT','VIS.UN.ISFXT'),  
									 treat_non_aoi_looks_as_missing = FALSE)

# set response window for prime
response_window_prime <- subset_by_window(data_prime, window_start_time = 2500, rezero= FALSE, remove= TRUE)
response_window_prime <- subset_by_window(response_window_prime, window_end_time = 4000, rezero= FALSE, remove= TRUE)

# analyze amount of trackloss by subjects and trials
(trackloss <- trackloss_analysis(data = response_window_prime))

# Remove trials with over 50% trackloss
response_window_clean_prime <- clean_by_trackloss(data = response_window_prime, trial_prop_thresh = .5)

# Assess mean trackloss for each participant
trackloss_clean_prime <- trackloss_analysis(data = response_window_clean_prime)


# LIST OF VALID TRIALS
## Keep only trials which are retained in clean_target AND clean_prime
merge_clean <- semi_join(trackloss_clean_target,trackloss_clean_prime, by = c("ID","AUD.STM"))



## PREPARING DATA FOR ANALYSIS


# Specify AOIS: Target and distractor

data <- make_eyetrackingr_data(cognatepriming_clean, 
							   participant_column = "ID",
							   trial_column = "AUD.STM",
							   time_column = "Timestamp",
							   trackloss_column = "OVERALL.TRACKLOSS",
							   item_columns = c("PRIME.STM"),
							   aoi_columns = c('VIS.TARGET.ISFXT','VIS.DISTR.ISFXT'), 
							   treat_non_aoi_looks_as_missing = FALSE)


#### Clean


# Subset to valid trials only, as defined in previous section
response_window_clean <- semi_join(data, merge_clean, by = c("ID","AUD.STM"))

# Exclude participants with 15 or less trials (half)
participant_summary <- describe_data(response_window_clean, 'VIS.TARGET.ISFXT', 'ID')

below_15trials <- participant_summary %>%
	filter(NumTrials <= 15)

response_window_clean <- anti_join(response_window_clean, below_15trials, by = "ID")

(final_summary <- describe_data(response_window_clean, 'VIS.TARGET.ISFXT', 'ID'))

sum(final_summary$NumTrials)
mean(final_summary$NumTrials)
sd(final_summary$NumTrials)


#### Subset analysis window

# Subset to full target/distractor image presentation window
response_window_clean <- subset_by_window(response_window_clean, window_end_time = 6750, rezero= FALSE, remove= TRUE)
response_window_clean <- subset_by_window(response_window_clean, window_start_time = 4750, rezero= TRUE, remove= TRUE) 


# SUBSET ANALYSIS WINDOW

# Analysis window onset: 200ms after target/distractor image onset
# Analysis window offset: 1300ms after target/distractor image onset
# Analysis window duration: 1100ms

### Reason for excluding time bins before 300ms and after 1300ms: 
### Before 200ms - Time needed for saccade to initiate first look 
##### Timebins between 0-200ms have less than 50% valid eye-tracking samples in AOIs (not looking at either target or distractor)
### After 1300ms - The duration of the first look is roughly 1300ms or less (the PTL has passed its peak and started dropping)
# Differences between conditions emerge early on, and keeping too much of the window will obscure effects

analysis_window <- subset_by_window(response_window_clean, window_start_time = 200, rezero= FALSE, remove= TRUE)
analysis_window <- subset_by_window(analysis_window, window_end_time = 1300, rezero= FALSE, remove= TRUE)





#### Aggregrate timebins + specify Target as AOI


# aggregate across trials within subjects in time analysis
response_time <- make_time_sequence_data(analysis_window, time_bin_size = 100, 
										 predictor_columns = c("LangGroup", "Condition", "Relatedness", "AgeGroup"),
										 aois = "VIS.TARGET.ISFXT")
#summary(response_time)




### Descriptives

# Number of trials per condition
NumTrials_condition <- response_time %>%
	group_by(Condition) %>%
	summarise(NumTrialsCondition = (length(Condition)/11)) # divided by 11 because there are 11 timebins (1100ms analysis window)
NumTrials_condition


# Number of trials in each condition contributed by each participant
NumTrials_subject_condition <- response_time %>%
	group_by(ID, Condition) %>%
	summarise(NumTrialsCondition = (length(Condition)/11)) 
NumTrials_subject_condition


# Number of participants after cleaning
print("Final participants after data cleaning")

response_time %>%
	dplyr::select(ID, AgeGroup, LangGroup) %>%
	unique() %>%
	group_by(AgeGroup, LangGroup) %>%
	summarise(N = n())



# homogenise code with Barcleona (added by GGC)
d <- response_time %>% 
	as_tibble() %>% 
	janitor::clean_names() %>% 
	


## ANALYSIS
### Growth curve
response_time_mono <- response_time[(response_time$LangGroup=="Monolingual"),]
#response_time_bi <- response_time[(response_time$LangGroup=="Bilingual"),]

response_time_mono_21 <- response_time[(response_time$AgeGroup=="21 months"),]
response_time_mono_25 <- response_time[(response_time$AgeGroup=="25 months"),]
response_time_mono_30 <- response_time[(response_time$AgeGroup=="30 months"),]


# Visualise data from each group
# Monolingual

print("21 month monolingual data")

plot(response_time_mono_21, predictor_column = "Condition", dv = "Prop") +
	theme_light() +
	xlab("Time from target & distractor image onset (ms)") +
	ylab("Proportion of time looking at target") +
	ylim(c(0:1))


print("21 month monolingual data with model fit curve")

# Plot monolingual data with model fit curve
model_time_sequence_plot_mono_21 <- lmer(Prop ~ Condition*(ot1 + ot2 + ot3) + 
										 	(1 | ID), 
										 data = response_time_mono_21, REML = FALSE)

plot(response_time_mono_21, predictor_column = "Condition", dv = "Prop", model = model_time_sequence_plot_mono_21) +
	theme_light() +
	xlab("Time from target & distractor image onset (ms)") +
	ylab("Proportion of time looking at target") +
	ylim(c(0:1))



print("25 month monolingual data")

plot(response_time_mono_25, predictor_column = "Condition", dv = "Prop") +
	theme_light() +
	xlab("Time from target & distractor image onset (ms)") +
	ylab("Proportion of time looking at target") +
	ylim(c(0:1))


print("30 month monolingual data")

plot(response_time_mono_30, predictor_column = "Condition", dv = "Prop") +
	theme_light() +
	xlab("Time from target & distractor image onset (ms)") +
	ylab("Proportion of time looking at target") +
	ylim(c(0:1))


# Bilingual
#plot(response_time_bi, predictor_column = "Condition", dv = "Prop") +
#  theme_light() +
#  xlab("Time from target & distractor image onset (ms)") +
#  ylab("Proportion of time looking at target") +
#  ylim(c(0:1))

# Plot monolingual data with model fit curve
model_time_sequence_plot_mono <- lmer(Prop ~ Condition*(ot1 + ot2 + ot3) + 
									  	(1 | ID), 
									  data = response_time_mono, REML = FALSE)




## All data combined

print("All monolingual data")

plot(response_time_mono, predictor_column = "Condition", dv = "Prop", model = model_time_sequence_plot_mono) +
	theme_light() +
	xlab("Time from target & distractor image onset (ms)") +
	ylab("Proportion of time looking at target") +
	ylim(c(0:1))


